# purge cache after deployment
name: Cloudflare Pages Purge Cache

on:
  check_run:
    types: [completed]
    branches: [main]

jobs:
  purge_cache:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
    if: github.event.check_run.name == 'Cloudflare Pages' && github.event.check_run.conclusion == 'success'
    steps:
      - name: Purge Cache
        run: |
          curl -X POST https://api.cloudflare.com/client/v4/zones/9bb83db883574ad9b59727773ac3b2e9/purge_cache \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
          -d '{"purge_everything": true}'